apiVersion: v1
kind: Service
metadata:
  name: {{ include "octant.fullname" . }}
  labels:
    {{- include "octant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.keycloakGatekeeper.enabled }}
      targetPort: http-sso
      {{- else }}
      targetPort: http
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "octant.selectorLabels" . | nindent 4 }}
